[package]
name = "fabricatio-config"
version = "0.1.3"
edition = "2024"
authors.workspace = true
license-file.workspace = true

[dependencies]
figment = { version = "0.10.19", features = ["env", "toml"] }
pyo3 = { version = "0.27.1", features = ["extension-module"] }
pythonize = "0.27.0"
serde_json = "1.0.145"
serde = { version = "1.0.228", features = ["derive"] }
validator = { version = "0.20.0", features = ["derive"] }
dotenvy = "0.15.7"
macro_utils = { path = "./crates/macro_utils" }
fabricatio-constants = {path = "../fabricatio-constants"}

