[package]
name = "fabricatio-memory"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
chrono = "0.4.42"
tantivy = { version = "0.25.0", features = ["mmap"] }
pyo3 = { version = "0.27.2", features = ["extension-module"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.146"
once_cell = "1.21.3"
pythonize = "0.27.0"
pyo3-stub-gen = "0.17.2"



[features]
stubgen = []
