[package]
name = "fabricatio-memory"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
chrono = "0.4.42"
tantivy = { version = "0.25.0", features = ["mmap"] }
pyo3 = { version = "0.27.1", features = ["extension-module"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
once_cell = "1.21.3"
pythonize = "0.27.0"

