[package]
name = "mcp-manager"
version = "0.1.1"
edition = "2024"

[dependencies]
futures = "0.3.31"
rmcp = { version = "0.12.0", features = ["client", "reqwest", "transport-child-process", "transport-io", "transport-streamable-http-client-reqwest"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
tokio = { version = "1.49.0", features = ["process", "rt-multi-thread", "sync"] }
which = "8.0.0"
pyo3 = { version = "0.27.2", optional = true, default-features = false }

thiserror = "2.0.17"

[dev-dependencies]
tokio = { version = "1.49.0", features = ["test-util"] }


