[package]
name = "fabricatio-anki"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
clap = { version = "4.5.53", features = ["derive"] }

pyo3 = { version = "0.27.1", features = ["extension-module"] }
deck_loader = { path = "./src/deck_loader" }
pythonize = "0.27.0"
sanitize-filename = "0.6.0"
regex = "1.12.2"
fabricatio-logger = { path = "../../crates/fabricatio-logger" }
serde_yaml2 = "0.1.3"

