[package]
name = "fabricatio-locale"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
polib = "0.3.0"

pyo3 = { version = ">=0.25.0", features = ["extension-module"] }
error-mapping = { path = "../../crates/error-mapping" }

