[package]
name = "fabricatio-thinking"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
fabricatio-core = { path = "../fabricatio-core", default-features = false }


pyo3 = { version = ">=0.24.2", features = ["extension-module"] }

