[package]
name = "fabricatio-thinking"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
fabricatio-logger = { path = "../../crates/fabricatio-logger" }


pyo3 = { version = ">=0.24.2", features = ["extension-module"] }

