[package]
name = "fabricatio-tool"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.27.1", features = ["extension-module"] }
pyo3-async-runtimes = { version = "0.27.0", features = ["tokio-runtime"] }
pythonize = "0.27.0"
rustpython-ast = { version = "0.4.0", features = ["visitor"] }
rustpython-parser = { version = "0.4.0" }
serde_json = "1.0.145"
mcp-manager = { path = "./crates/mcp-manager" }
signify = { path = "./crates/signify" }
rmcp = { version = "0.8.5", features = ["transport-sse-client-reqwest", "transport-streamable-http-client-reqwest"] }
fabricatio-logger = { path = "../../crates/fabricatio-logger" }
