[package]
name = "fabricatio-tool"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.27.2", features = ["extension-module"] }
pyo3-async-runtimes = { version = "0.27.0", features = ["tokio-runtime"] }
pythonize = "0.27.0"
rustpython-ast = { version = "0.4.0", features = ["visitor"] }
rustpython-parser = { version = "0.4.0" }
serde_json = "1.0.148"
mcp-manager = { path = "../../crates/mcp-manager", features = ["into_pyerr"] }
signify = { path = "../../crates/signify" }
rmcp = { version = "0.12.0", features = ["transport-streamable-http-client-reqwest"] }
fabricatio-logger = { path = "../../crates/fabricatio-logger" }

ignore = { version = "0.4.25" }

error-mapping = { path = "../../crates/error-mapping", features = ["pythonize", "serde_json"] }
rayon = "1.11.0"



