[package]
name = "mcp-manager"
version = "0.1.0"
edition = "2024"

[dependencies]
futures = "0.3.31"
rmcp = { version = "0.11.0", features = ["client", "reqwest", "transport-child-process", "transport-io", "transport-streamable-http-client-reqwest"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
tokio = { version = "1.48.0", features = ["process", "rt-multi-thread", "sync"] }
which = "8.0.0"



[dev-dependencies]
tokio = { version = "1.48.0", features = ["test-util"] }

