[package]
name = "error-mapping"
version = "0.1.1"
edition = "2024"
authors.workspace = true
license-file.workspace = true

[dependencies]
epub-builder = { version = "0.8.2", default-features = false, optional = true }
git2 = { version = "0.20.2", default-features = false, optional = true }
pyo3 = { version = "0.27.1", default-features = false }


[features]
git2 = ["dep:git2"]
epub-builder = ["dep:epub-builder"]
