[package]
name = "fabricatio-novel"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
regex = "1.12.2"
epub-builder = "0.8.0"
thiserror = "2.0.17"
mime_guess = "2.0.5"
pyo3 = { version = ">=0.24.2", features = ["extension-module"] }

