[project]
name = "fabricatio-novel"
version = "0.1.7"
description = "An extension of fabricatio"
readme = "README.md"
license = "MIT"
authors = [
    { name = "Whth", email = "zettainspector@foxmail.com" }
]
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Programming Language :: Python :: Implementation :: CPython",
    "Typing :: Typed",
]
requires-python = ">=3.12,<3.15"
dependencies = [
    "fabricatio-character",
    "fabricatio-core",
    "pydantic>=2.11.9",
]

[dependency-groups]
dev = [
    "pytest",
]

[project.optional-dependencies]

full = [
    "fabricatio-novel[workflows,cli]"
]

workflows = ["fabricatio-actions"]
cli = [
    "fabricatio-novel[workflows]",
    "questionary>=2.1.0",
    "typer-slim[standard]>=0.15.2",
]


[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[tool.maturin]
python-source = "python"
module-name = "fabricatio_novel.rust"


[project.scripts]
fanvl = "fabricatio_novel.cli:app"

[project.urls]
Homepage = "https://github.com/Whth/fabricatio"
Repository = "https://github.com/Whth/fabricatio"
Issues = "https://github.com/Whth/fabricatio/issues"

[[tool.uv.index]]
url = "https://mirrors.aliyun.com/pypi/simple/"
default = true

[tool.uv.sources]
fabricatio-character = { workspace = true }

[[tool.uv.index]]
url = "https://mirrors.huaweicloud.com/repository/pypi/simple"

[[tool.uv.index]]
url = "https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple"
