[package]
name = "fabricatio-webui"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
axum = "0.8.8"

pyo3 = { version = ">=0.24.2", features = ["extension-module"] }
tokio = { version = "1.48.0", features = ["rt-multi-thread"] }
tower-http = { version = "0.6.8", features = ["cors", "fs"] }
pyo3-async-runtimes = { version = "0.27.0", features = ["tokio-runtime"] }

fabricatio-logger = { path = "../../crates/fabricatio-logger" }
error-mapping = { path = "../../crates/error-mapping" }



[build-dependencies]
which = "8.0.0"