[package]
name = "fabricatio-diff"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]

pyo3 = { version = ">=0.24.2", features = ["extension-module"] }
rayon = "1.11.0"
similar = "2.7.0"
strsim = "0.11.1"
pyo3-stub-gen = "0.17.2"

[features]
stubgen = []
