[package]
name = "fabricatio-core"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
blake3 = "1.8.2"
handlebars = "6.3.2"
pyo3 = { version = "0.27.2" }
pythonize = "0.27.0"
rayon = "1.11.0"
serde_json = "1.0.147"
unicode-segmentation = "1.12.0"
walkdir = "2.5.0"
serde = { version = "1.0.228", features = ["derive"] }
strum = { version = "0.27.2", features = ["derive"] }
whichlang = "0.1.1"
scanner = { path = "../../crates/scanner" }
error-mapping = { path = "../../crates/error-mapping", features = ["handlebars", "pythonize"] }
fabricatio-constants = { path = "../../crates/fabricatio-constants" }
fabricatio-logger = { path = "../../crates/fabricatio-logger" }
fabricatio-config = { path = "../../crates/fabricatio-config" }
once_cell = "1.21.3"
path-clean = "1.0.1"
postcard = { version = "1.1.3", features = ["use-std"] }
pyo3-stub-gen = "0.17.2"
chrono = "0.4.42"
cfg-if = "1.0.4"

[dev-dependencies]
tempfile = "3.24.0"

[features]
default = ["pyo3/extension-module"]
stubgen = []


