[package]
name = "fabricatio-core"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
blake3 = "1.8.2"
handlebars = "6.3.2"
pyo3 = { version = "0.27.2", features = ["extension-module"] }
pythonize = "0.27.0"
rayon = "1.11.0"
serde_json = "1.0.145"
unicode-segmentation = "1.12.0"
walkdir = "2.5.0"
serde = { version = "1.0.228", features = ["derive"] }
strum = { version = "0.27.2", features = ["derive"] }
bincode = { version = "2.0.1", features = ["serde"] }
whichlang = "0.1.1"
fabricatio-logger = { path = "../../crates/fabricatio-logger" }
fabricatio-config = { path = "../../crates/fabricatio-config" }
scanner = { path = "../../crates/scanner" }
chrono = "0.4.42"
once_cell = "1.21.3"
path-clean = "1.0.1"
error-mapping = { path = "../../crates/error-mapping", features = ["handlebars", "pythonize"] }

[dev-dependencies]
tempfile = "3.23.0"