[package]
name = "fabricatio-core"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
blake3 = "1.8.2"
handlebars = "6.3.2"
pyo3 = { version = "0.27.2", features = ["extension-module"] }
pythonize = "0.27.0"
rayon = "1.11.0"
serde_json = "1.0.146"
unicode-segmentation = "1.12.0"
walkdir = "2.5.0"
serde = { version = "1.0.228", features = ["derive"] }
strum = { version = "0.27.2", features = ["derive"] }
whichlang = "0.1.1"
scanner = { path = "../../crates/scanner" }
macro-utils = { path = "../../crates/macro-utils" }
error-mapping = { path = "../../crates/error-mapping", features = ["handlebars", "pythonize"] }
chrono = "0.4.42"
once_cell = "1.21.3"
path-clean = "1.0.1"
postcard = { version = "1.1.3", features = ["use-std"] }
pyo3-stub-gen = "0.17.2"
tracing-subscriber = { version = "0.3.22", default-features = false, features = ["env-filter", "chrono"] }
tracing = "0.1.44"
tracing-appender = "0.2.4"
directories-next = "2.0.0"
dotenvy = "0.15.7"
figment = { version = "0.10.19", features = ["env", "toml"] }
validator = { version = "0.20.0", features = ["derive"] }
cfg-if = "1.0.4"

[dev-dependencies]
tempfile = "3.23.0"

[features]
default = ["pymodule"]
stubgen = []
pymodule = []

