[package]
name = "fabricatio-stubgen"
version = "0.1.2"
edition = "2024"
authors.workspace = true
license-file.workspace = true

[dependencies]
pyo3-stub-gen = "0.17.2"
fabricatio-core = { path = "../../packages/fabricatio-core", features = ["stubgen"], default-features = false }
fabricatio-memory = { path = "../../packages/fabricatio-memory", features = ["stubgen"], default-features = false }
fabricatio-diff = { path = "../../packages/fabricatio-diff", features = ["stubgen"], default-features = false }
fabricatio-checkpoint = { path = "../../packages/fabricatio-checkpoint", features = ["stubgen"], default-features = false }



[build-dependencies]
pyo3-build-config = "0.27.2"
