[package]
name = "scanner"
version = "0.1.2-dev2"
edition = "2024"
authors.workspace = true
license-file.workspace = true

[dependencies]
moka = { version = "0.12.12", features = ["sync"] }
pep508_rs = "0.9.2"
pyo3 = "0.27.2"
rayon = "1.11.0"
walkdir = "2.5.0"
once_cell = "1.21.3"
