[package]
name = "fabricatio-typst"
edition = "2024"
[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
biblatex = "0.11.0"
nucleo-matcher = "0.3.1"
pyo3 = { version = "0.27.2" }
pythonize = "0.27.0"
rayon = "1.11.0"
regex = "1.12.2"
tex2typst-rs = "0.4.1"

clap = { version = "4.5.53", features = ["derive"] }

fabricatio-logger = { path = "../../crates/fabricatio-logger" }
serde_yaml2 = "0.1.3"
[build-dependencies]
pyo3-build-config = "0.27.0"

[features]
default = ["pyo3/extension-module"]
