[package]
name = "fabricatio-typst"
edition = "2024"
[lib]
crate-type = ["cdylib"]

[dependencies]
biblatex = "0.11.0"
nucleo-matcher = "0.3.1"
pyo3 = { version = "0.27.2", features = ["extension-module"] }
pythonize = "0.27.0"
rayon = "1.11.0"
regex = "1.12.2"
tex2typst-rs = "0.4.1"
typst_conversion = { path = "src/typst_conversion" }

clap = { version = "4.5.53", features = ["derive"] }

fabricatio-logger = {path = "../../crates/fabricatio-logger"}
serde_yaml2 = "0.1.3"
