[package]
name = "fabricatio-checkpoint"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
blake3 = "1.8.2"
fabricatio-logger = { path = "../../crates/fabricatio-logger" }

git2 = { version = "0.20.3", features = ["vendored-libgit2"], default-features = false }
moka = { version = "0.12.12", features = ["sync"] }

pyo3 = { version = ">=0.24.2", features = ["extension-module"] }
error-mapping = { path = "../../crates/error-mapping", features = ["git2"] }
utils = { path = "../../crates/utils" }
rayon = "1.11.0"
pyo3-stub-gen = "0.17.2"




[features]
default = ["pyo3/extension-module"]
stubgen = []
